// Barrel for this sample's projenrc customizations. Keeps .projenrc.ts thin --
// import the factories from here and call them.
//
// `./tasks` is the provider-agnostic tasks module: build tasks + the multi-phase
// deploy rail. CI for this sample is generated by the monorepo ROOT .projenrc.ts
// (GitHub Actions build/e2e/cleanup per pattern), not by this subproject, so there is
// deliberately no per-provider workflow factory here.
export { createBuildTasks, createDeployTasks } from './tasks';
