name: "s3mrap-crr: build"
on:
  pull_request:
    paths: ['s3mrap-crr/**']
  push:
    branches: [main, S3MRAP]
    paths: ['s3mrap-crr/**']
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: s3mrap-crr
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx projen build
